apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
    - name: github
      mappingMethod: claim
      type: GitHub
      github:
        clientID: 2dd6eed6e8e0865369d3
        clientSecret:
          name: clientsecret-github
        teams:
          - CCI-MOC/ops
