apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: clientsecret-github
  namespace: openshift-config
spec:
  backendType: secretsManager
  roleArn: arn:aws:iam::574733721584:role/secretreader-cluster1
  data:
    - key: cluster/cluster1/openshift-config/sso-clientsecret-github
      name: clientSecret
