apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../bundles/external-secrets

  - ../../base/rbac.authorization.k8s.io/clusterrolebindings/cluster-admins-rb
  - ../../base/rbac.authorization.k8s.io/clusterrolebindings/self-provisioners
  - ../../base/user.openshift.io/groups/cluster-admins

  - clusterversions
  - externalsecrets
  - oauths
