apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/rbac.authorization.k8s.io/clusterrolebindings/cluster-admins-rb
  - ../../base/user.openshift.io/groups/cluster-admins

  - clusterversions
